
FROM python:3.12-bookworm

WORKDIR /mlflow

RUN pip install mlflow

ENV BACKEND_URI=sqlite:///mlflow.db

EXPOSE 8080

# CMD [ "mlflow", "server", "--backend-store-uri", $BACKEND_URI, "--host", "0.0.0.0", "--port", "8080" ]
# CMD mlflow server --backend-store-uri ${BACKEND_URI} --host 0.0.0.0 --port 8080